import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js';
import { isCoarsePointer, reducedMotion, states } from './config.js';

export class WebGLScene {
  constructor() {
    this.canvas=document.createElement('canvas');this.canvas.id='narrative-canvas';this.canvas.setAttribute('aria-hidden','true');document.body.prepend(this.canvas);
    this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,alpha:true,antialias:!isCoarsePointer,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,isCoarsePointer?1.1:1.5));
    this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(38,1,.1,100);this.camera.position.set(0,1.4,7);this.group=new THREE.Group();this.scene.add(this.group);
    this.scene.add(new THREE.HemisphereLight(0xf5eee1,0x24120f,2));const key=new THREE.DirectionalLight(0xffffff,2.3);key.position.set(4,6,5);this.scene.add(key);const red=new THREE.PointLight(0xe43d25,14,12);red.position.set(-3,2,3);this.scene.add(red);
    this.pointer=new THREE.Vector2();this.target=new THREE.Vector2();this.state='idea';this.makeProduct();this.makePrinter();this.makeFarm();this.resize();addEventListener('resize',()=>this.resize(),{passive:true});if(!isCoarsePointer)addEventListener('pointermove',e=>this.target.set(e.clientX/innerWidth-.5,e.clientY/innerHeight-.5),{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.render();});this.render();
  }
  makeProduct(){const shape=new THREE.Shape();shape.moveTo(-1.25,-.7);shape.lineTo(-.45,-.7);shape.lineTo(-.45,-.12);shape.lineTo(.45,-.12);shape.lineTo(.45,-.7);shape.lineTo(1.25,-.7);shape.lineTo(1.25,.72);shape.lineTo(.45,.72);shape.lineTo(.45,.26);shape.lineTo(-.45,.26);shape.lineTo(-.45,.72);shape.lineTo(-1.25,.72);shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:.42,bevelEnabled:true,bevelSegments:2,bevelSize:.05,bevelThickness:.05});geo.center();this.product=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x242421,roughness:.82,metalness:.04}));this.product.rotation.set(-.26,.34,0);this.group.add(this.product);this.wire=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0xe43d25,transparent:true,opacity:.9}));this.wire.rotation.copy(this.product.rotation);this.group.add(this.wire);this.layers=new THREE.Group();for(let i=0;i<11;i++){const layer=new THREE.Mesh(new THREE.BoxGeometry(2.54,.045,.46),new THREE.MeshStandardMaterial({color:i===7?0xe43d25:0x403f39,roughness:.92}));layer.position.y=-.7+i*.12;this.layers.add(layer)}this.layers.visible=false;this.group.add(this.layers);}
  makePrinter(){this.printer=new THREE.Group();const frameMat=new THREE.MeshStandardMaterial({color:0x2a2a27,roughness:.8});const bar=(x,y,z,s)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...s),frameMat);m.position.set(x,y,z);this.printer.add(m)};bar(-1.8,0,0,[.08,2.4,.08]);bar(1.8,0,0,[.08,2.4,.08]);bar(0,1.1,0,[3.7,.08,.08]);bar(0,-.95,0,[3.4,.1,2.15]);this.nozzle=new THREE.Mesh(new THREE.ConeGeometry(.14,.32,4),new THREE.MeshStandardMaterial({color:0xe43d25,roughness:.65}));this.nozzle.position.set(0,.76,.1);this.nozzle.rotation.x=Math.PI;this.printer.add(this.nozzle);this.printer.visible=false;this.group.add(this.printer)}
  makeFarm(){this.farm=new THREE.Group();for(let i=0;i<5;i++){const c=this.printer.clone();c.scale.setScalar(.35);c.position.set((i%3-1)*1.25,.1,(Math.floor(i/3)-.5)*1.2);this.farm.add(c)}this.farm.visible=false;this.group.add(this.farm);this.order=new THREE.Mesh(new THREE.BoxGeometry(.28,.28,.28),new THREE.MeshStandardMaterial({color:0xe43d25,emissive:0x5b120b,roughness:.55}));this.order.visible=false;this.group.add(this.order)}
  setState(id){this.state=states[id]?.mode||'idea';const s=this.state;this.product.visible=!['network'].includes(s);this.wire.visible=['idea','layers'].includes(s);this.layers.visible=['layers','custom','order'].includes(s);this.printer.visible=['layers','custom','order'].includes(s);this.farm.visible=s==='network';this.order.visible=['order','network'].includes(s);this.product.material.color.set(s==='catalog'?0xd9d3c6:0x242421);this.product.scale.set(s==='custom'?1.17:1,s==='custom'?.82:1,1);}
  resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight,false)}
  render(){if(document.hidden)return;this.pointer.lerp(this.target,.045);this.group.rotation.y+=((this.pointer.x*.25)-this.group.rotation.y)*.04;this.group.rotation.x+=((-.15+this.pointer.y*.14)-this.group.rotation.x)*.04;this.nozzle&&this.nozzle.position.set(Math.sin(performance.now()*.001)*.65,.76,.1);if(this.order.visible)this.order.position.set(-1.6+((Math.sin(performance.now()*.001)+1)*1.6),.05,.5);this.renderer.render(this.scene,this.camera);if(!reducedMotion)requestAnimationFrame(()=>this.render())}
}
